### PR TITLE
Fix rake_version method

### PR DESCRIPTION
**Pull request by AmirMingaliev**
Hey, @jondeandres I've found the typo, which causes #396, I think. Could you kindly review this PR?

### CODE REVIEW

**Comment by jondeandres** [comment]
Thanks @AmirMingaliev, I'd say that was the cause of the problem yes :smile:. I'll merge and release a new version.

Thanks again!

**Comment by stevenharman** [comment]
Phew, this just hit us after a seemingly mundane upgrade of a few dependencies. We're awaiting a new release of the `rollbar` gem. Thanks!

**Comment by AmirMingaliev** [comment]
@jondeandres great!

**Comment by lksv** [comment]
Should be nice to update also web pages which refer to last gem version:
* https://rollbar.com/docs/notifier/rollbar-gem/
* and the one which is showed when new project is created (at rollbar.com web )

**Pull request merged**
