### PR TITLE
Trace exception local variables and args per frame

### PR DESCRIPTION
**Pull request by mrap**
New configuration options and defaults
config.locals.enabled = off
config.locals.max_trace_frames = 100

Turned off by default because this may not be performant just yet!
1. Stores each Ruby process' local vars and method arguments
2. When gathering exception data, "replay" over each frame to get the variables for that frame's context
3. Dump the cache and repeat

### CODE REVIEW

**Comment by coryvirok** [comment]
@rokob can you take this over? This would be awesome to have in the SDK!

**Comment by guyzmo** [comment]
hey! 🙌 just a note to express my interest in this feature as well, being a pythonista doing some Ruby now, I'm surprised to see that such a thing is that problematic in Ruby. I'm sadly unable to help on that 😕

**Comment by echan00** [comment]
Interested in this feature as well

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Can you review this PR?

**Comment by ArturMoczulski** [comment]
This is conflicting with current master and I believe local vars in frames have been implemented since. If this is still requested and valid I will reopen.

**Pull request closed without merging**
