### PR TITLE
GitHub Issue #657: rollbar.js version 2.3.1 is now available. (This project is currently using version 2.1.0)

### PR DESCRIPTION
**Pull request by ArturMoczulski**
In response to https://github.com/rollbar/rollbar-gem/issues/657 this PR updates the rollbar.js version included in the gem. Note, I updated to the latest tag `v2.3.7` instead of requested `v2.3.1`.

Ready for review.

### CODE REVIEW

**Comment by rokob** [comment]
👍

**Comment by vfonic** [comment]
I'm still seeing the warning that new version of rollbar.js is available. Has this change been released? Thanks!

**Comment by ArturMoczulski** [comment]
@vfonic this change has not been released just yet. It will be included in the next tag. In meantime, if you want to get rid of the warnings, you can try to use the `master` branch of the gem.

**Comment by vfonic** [comment]
Yeah, it's been 2 months so I was wondering how long does it usually take to get such a small change in?

I'll wait nevertheless. I'm not sure if I'll have much use of telemetry. :)

Thanks!

**Comment by ArturMoczulski** [comment]
@vfonic we are planning to release the next gem tag around the end of this month, so very soon :)

**Pull request merged**
