### PR TITLE
Remove MultiJson dependency.

### PR DESCRIPTION
**Pull request by printercu**
To use Oj add `Rollbar::JSON.oj!` in initializer.

There is no need in MultiJson while it's set up only to use Oj. If someone want to use any other adapter, he can just redefine `load & dump` methods in `Rollbar::JSON`.

### CODE REVIEW

**Comment by printercu** [comment]
https://github.com/rails/rails/pull/10576 about multijson

**Comment by jondeandres** [comment]
Hey @printercu, thank you very much for this. We'd consider removing multi_json dependency since it will not be supported any more. But I've found some issues and questions.

- Currently we support ruby 1.8, although we are thinking on stop the ruby 1.8 support soon. Which consequences will have this change on this?
- Now we detect the default adapter used by MultiJson and we always try to use Oj if it's found. With this change users would need to execute `Rollbar::JSON.oj!` in order to continue using Oj. This is a kind of interface breaking and probably it'd be better to run `oj!` ourself if `Oj` is found. Probably on the setup method we have.

What do you think?

Thanks.

**Comment by printercu** [comment]
Second seems to be reasonable. I'll add this.
What about 1.8? Doesn't it have `json` in stdlib? I haven't used it for a long time.

**Comment by printercu** [comment]
@jondeandres What setup method you've told about? Can't find any matching.

**Comment by jondeandres** [comment]
oh, true @printercu. I think we removed it on a time when we didn't have multi_son. if you take a look at the history for lib/rollbar/json.rb you can find it. We used it to load oj when it was a depedency in the gem.

so, we'd need to setup on Rollbar initialization the library to be used.

**Comment by printercu** [comment]
updated

**Comment by jondeandres** [comment]
Hey @printercu, thanks. It looks pretty nice. I'll review it better, do some tests and figure out what is the scenario with ruby 1.8.

**Comment by printercu** [comment]
@jondeandres Hi! any update on it?

**Comment by jondeandres** [comment]
Hi @printercu, no yet sorry. We've been working on other stuff recently. We'll try to prioritize this in our next gem round :smile:.

Thank you very much for this, we really appreciate it.

**Comment by printercu** [comment]
Cool, thank you!

**Comment by rokob** [comment]
Ruby 1.8 does not come with the json gem bundled with the stdlib, that started with 1.9. The json gem supports 1.8, you just have to list it as a runtime dependency.

**Comment by rokob** [comment]
1.8 also does not come with Rubygems

**Comment by rokob** [comment]
This is a good change that we should merge, but we need to resolve the < 1.9 issues and remove the multi_json runtime dependency from the gemspec.

**Comment by ArturMoczulski** [comment]
I'm closing this PR since there are conflicts with latest `master`. If you still want to changes from this PR, please sync with the latest master

**Pull request closed without merging**
