### PR TITLE
Attempting to get Travis to test jruby with different Java versions a…

### PR DESCRIPTION
**Pull request by coryvirok**
…nd not ignore jruby-19mode failures. @jondeandres cc @brianr

### CODE REVIEW

**Comment by jondeandres** [comment]
@coryvirok tests are failing. do you want me to look at this at any moment?

**Comment by jondeandres** [comment]
@coryvirok :+1: to merge this?

**Comment by coryvirok** [comment]
Oops, sorry. I didn't see your last message.

**Comment by jondeandres** [comment]
no worry @coryvirok

**Pull request merged**
