### PR TITLE
Allow to send a custom message on the extra hash

### PR DESCRIPTION
**Pull request by olvap**
I didn't find any way to send a custom message in the implementation, so I added this line to send it on the extra hash.
You will have to use it like this

~~~ ruby
Rollbar.info "title", custom: {some: 'value'}
~~~

I didn't created any test because i not sure if it is the correct approach. What do you think?

### CODE REVIEW

**Comment by brianr** [comment]
Thanks @olvap !

The intended way to do it now is like this:

```ruby
Rollbar.scope({:custom => {:some => "value"}}).info("title")
```

Does that make sense?

We should document this better, and maybe add a helper method...

**Comment by olvap** [comment]
In that case, I could added to the doc.

**Comment by olvap** [comment]
May be a helper is a good idea.

**Comment by jondeandres** [comment]
@brianr what's the idea about this? if we decide to set the `custom` value using `scope` or `scoped` then we should document it. 

@olvap having an extra argument that takes part for the `extra` value and part for `custom` value can be confusing IMHO. But it's clear we should improve our docs or the interface for this.

**Comment by olvap** [comment]
I'll close this PR for now.

**Pull request closed without merging**
