### PR TITLE
Ruby 2.6.3 and latest Rails 5.x releases

### PR DESCRIPTION
**Pull request by waltjones**
Gets travis up to date with current Ruby and Rails versions.

Also, Ruby 2.6.x builds have been failing because of an rspec-command and/or shellout issue. Testing with latest shellout didn't solve this, so the rollbar-rails-runner specs are skipped in 2.6.x for now.

### CODE REVIEW

**Comment by bf4** [comment]
what was the failure?  I *just* upgraded from 5.0.7 to 5.1.1 on ruby 2.6.2 and started getting "rails5_runner': uninitialized constant Rails::Command (NameError)" from `bin/rollbar-rails-runner`.  It's resolved by adding 'require 'rails/command'` which was introduced in Rails 5.1, but I can't tell why no one else may have reported this issue, so am debugging my gemfile.  Leaving a note here in case it helps.  Meanwhile, changed to using my ruby-fu and changed our runner jobs to use`bundle exec ruby -rbundler/setup -rrails/command -S rollbar-rails-runner`

**Comment by waltjones** [comment]
@bf4 I will take a look, but do note that the issues detailed in this PR and in the linked PR have only to do with RSpec and Travis dependencies to automate testing of the rollbar-rails-runner. There were no problems observed with the rails runner itself.

**Comment by bf4** [comment]
Thanks @waltjones I couldn't tell, and because it's so odd that no one else has reported this, I wondered if it deserved a new issue.

**Comment by waltjones** [comment]
Looks like a new issue would be best. Thank you!

**Comment by bf4** [comment]
Made issue https://github.com/rollbar/rollbar-gem/issues/935

**Pull request merged**
