### PR TITLE
Update rollbar.js snippet to 1.9.3

### PR DESCRIPTION
**Pull request by jondeandres**

### CODE REVIEW

**Comment by coryvirok** [comment]
@jondeandres there are some failing tests in Travis. Can you take a look?

**Comment by jondeandres** [comment]
@coryvirok tests are passing now. we want to merge this or we would be interested on pushing rollbar js 2.x? @rokob ?

**Comment by coryvirok** [comment]
Let's push the latest rollbar.js. It should be backwards compatible with 1.9.x.

**Comment by jondeandres** [comment]
Ok, I opened https://github.com/rollbar/rollbar-gem/pull/600 for that

**Pull request closed without merging**
