### PR TITLE
Send rollbar_comment during deploys

### PR DESCRIPTION
**Pull request by wemcdonald**
Pretty self-explanatory.

FWIW I'm using this with the `capistrano-pending` gem to publish a changelog as the comment (I'm not on Github so I don't get the free commit log):

```
set :rollbar_comment, Proc.new { `cap #{fetch :stage} deploy:pending`.split("\n").grep(/^    /).join("\n\n") }
```

### CODE REVIEW

**Comment by Crisfole** [comment]
Hey there, this is great. Thanks!

Can you add a test or two for this?

Once the tests pass we'll take a second look and hopefully merge it! It would fix my (poor attempt) in #398.

**Comment by Crisfole** [comment]
Ok. So I'm told that adding Capistrano tests is challenging/difficult. What I'll do is test this manually once the other tests pass. :D

**Comment by printercu** [comment]
Maybe it's better to make `current_revision` configured? I've redefined it with
```ruby
# deploy.rb
require 'rollbar/capistrano'

def current_revision
  `git log #{branch} -n 1 --pretty=format:"%H"`
end

```

**Comment by jondeandres** [comment]
@wemcdonald I'm worried about this change cause it forces a user input, no? I guess some customers have automated deploys where they can't enter that value.

**Comment by coryvirok** [comment]
I agree with Jon. Can we make this optional and not enabled by default?

**Comment by jondeandres** [comment]
We can do this yes. I think we should first tests this manually since we don't have capistrano tests for now.

**Comment by wemcdonald** [comment]
@jondeandres I just used the interactive case as an example since it seemed the most self-explanatory. See my first comment above for something non-interactive.

@coryvirok is your concern the same, or that we're including the key in the request with a null value? That doesn't seem like it's different from any of the other values...

**Comment by coryvirok** [comment]
I was agreeing with Jon about not requiring users to enter a comment. After reading your README change more closely, it says that it's optional. Which is 👍 by me.

**Comment by wemcdonald** [comment]
I just updated the text in the readme to describe what the example does and to provide another suggestion. I didn't include my use case because `deploy:pending` is no longer standard.

**Comment by rokob** [comment]
I can't think of a natural default comment, but it is something that is easy to add if there is something obvious that I am missing. Otherwise, I think we should merge this.

**Comment by mengqing** [comment]
+1, looking forward to get this feature integrated!! Also, just wondering if we can more control / configuration on what we can set as the comment?

Eg; we want to tag an environment variable on the remote server as a deploy comment once deployed

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Can you review this PR?

**Comment by ArturMoczulski** [comment]
LGTM. Merging.

@mengqing you should be able to easily configure the comment using
```
set :rollbar_comment, Proc.new {}
```

**Pull request merged**
