### PR TITLE
Guard against the retry key being set and no retry_count present

### PR DESCRIPTION
**Pull request by aselder**
This fixes https://github.com/rollbar/rollbar-gem/issues/345

### CODE REVIEW

**Comment by jondeandres** [comment]
@aselder which version of sidekiq are you using?

when `msg_or_context['retry_count']` is `nil`, which value of `msg_or_context["retry"]` do you have?

**Comment by aselder** [comment]
@jondeandres We're currently on  sidekiq 2.17.3. We're planning on upgrading soon, but this is a blocker on us using rollbar until it's fixed.

Not sure what the value of  msg_or_context["retry"] is, but I'll try to dig it up with some debuggers.

**Comment by aselder** [comment]
@jondeandres msg_or_context["retry"] is set to 'true' for us, but no retry_count

**Comment by pacoguzman** [comment]
Thanks @aselder I think this is more reliable than the existing version so LGTM. We've checked `retry` because you can configure your worker to not be retried so in that case `retry` has a false value and we don't want to skip the report in that case. And for retriable workers we'll check the retry_count but as you've found we need to be sure we have a value for that key

Good catch thank you!

**Comment by jondeandres** [comment]
@aselder @pacoguzman we've release 2.6.2 with this fix. Thanks.

**Pull request merged**
