### PR TITLE
Issue 841: Build RSpec coverage of the Capistrano wrapper

### PR DESCRIPTION
**Pull request by ArturMoczulski**
Full test coverage for Capistrano deployment tasks and deployment API class.

### CODE REVIEW

**Comment by ArturMoczulski** [comment]
@waltjones this is ready for review. Can you take a look?

**Comment by waltjones** [comment]
@ArturMoczulski Sure, I'll start taking a look tomorrow.

On the codacy issue, you'll need to add `# rubocop:disable Bundler/DuplicatedGem` to the second occurrence. (Line 43. See line 45 as an example.) Codacy isn't smart enough to understand the `if`/`elsif` in gemfiles.

**Comment by ArturMoczulski** [comment]
Got it. Thx

**Comment by waltjones** [comment]
Simplecov reports 100% coverage on capistrano_tasks.rb and deploy.rb! Nice work.

LGTM

**Comment by domininik** [comment]
This pull request contains significant fix for `Rollbar::Deploy` module.

Currently my deploy fails with `NoMethodError: undefined method `parse' for Rollbar::JSON:Module`
when `rollbar:deploy_started` is executed. That's because `build_result` method tries to call `parse` on `Rollbar::JSON` instead of `::JSON`.

We are forced to downgrade `rollbar` in our projects back to `2.18.2`.
When can we expect it to be released? :)

**Comment by domininik** [comment]
@waltjones @ArturMoczulski let me mention you to ensure you didn't miss the notification :)

**Comment by waltjones** [comment]
@domininik I'll talk with @ArturMoczulski today about a release.

**Comment by ArturMoczulski** [comment]
I'm going to put together a release now

**Comment by ArturMoczulski** [comment]
Released in `v2.19.3`

**Comment by domininik** [comment]
Thanks!

**Pull request merged**
