### PR TITLE
specify delayed_job queue

### PR DESCRIPTION
**Pull request by inquisitivus**
Hi!
This is for my question in #563.

### CODE REVIEW

**Comment by rokob** [comment]
This will certainly break the existing behaviour where people assume jobs are run on the default delayed_job queue. It should be possible to add this feature, but doing it this way won't work.

**Comment by rokob** [comment]
One approach would be to add an option similar to https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/configuration.rb#L163 in the configuration for delayed_job here https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/configuration.rb#L148, and then if a queue is set on the delayed job class you can use that in the call method otherwise use the current default way of doing it.

**Comment by inquisitivus** [comment]
I've changed my bits according to your advice. Is it ok now?

**Comment by rokob** [comment]
Looks good to me, thanks!

**Pull request merged**
