### PR TITLE
Style tweaks for sidekiq handler

### PR DESCRIPTION
**Pull request by jjb**
style-only -- partial work previously done in #197, which i will redo based on this branch

### CODE REVIEW

**Comment by jondeandres** [comment]
Thanks @jjb!

it's nice for me, we'll wait for the specs to pass and then we can merge it.

**Comment by brianr** [comment]
Merged, thanks @jjb !

**Comment by brianr** [comment]
Released in 1.4.3 (now on rubygems)

**Comment by jjb** [comment]
:dango:

**Pull request merged**
