### PR TITLE
Ensure we test all Ruby permutation with Rails correctly

### PR DESCRIPTION
**Pull request by joneslee85**
What is this about?

* I update all gemfiles to latest version if there is. 
* I add gemfile for Rails 42
* I add Ruby 2.2.2
* Exclude Ruby that Rails does not support
* Remove -head Ruby implementations

### CODE REVIEW

**Comment by jondeandres** [comment]
Hey @joneslee85, thanks for the PR. I'll review this soon. Tests are not passing, take a look at that please.

Thanks again!

**Comment by joneslee85** [comment]
@jondeandres it's in progress

**Comment by joneslee85** [comment]
@jondeandres It's ready to go! :)

**Comment by brianr** [comment]
This looks good to me. Thanks @joneslee85 !

@jondeandres, can we merge this?

**Pull request merged**
