### PR TITLE
Remove extra multi_json requires

### PR DESCRIPTION
**Pull request by albertyw**
As a response to the comment at https://github.com/rollbar/rollbar-gem/commit/2f1a593faaf0b7354d216738f7a6c023a3e7a4ce

### CODE REVIEW

**Comment by brianr** [comment]
Oo, thanks! Will merge once the build comes back green.

**Comment by joneslee85** [comment]
@brianr have a look into my PR https://github.com/rollbar/rollbar-gem/pull/256, I manage to get it green

**Comment by albertyw** [comment]
I'm happy to rebase this PR to rerun tests.

**Comment by jondeandres** [comment]
@albertyw version 2.0.1 has been released.

Thanks for this!

**Pull request merged**
