### PR TITLE
Propose more resilient boot crash logging

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by rokob** [comment]
This seems like an okay change to me, anyone else have an opinion? It is just a doc change, but it makes sense.

**Comment by bf4** [comment]
@rokob Thanks for the quick review.  This is the code we're using now. Our app didn't boot last night and we didn't get any notifications.  This is one of our fixes to address that :)

**Comment by bf4** [comment]
@rivkahstandig3636 🌈

**Comment by bf4** [comment]
I just had a sidekiq boot failure which rollbar didn't successfully notify me of.. due to sidekiq failing, and came back to the repo to look for where it might be like this solution, but see it was removed in https://github.com/rollbar/rollbar-gem/pull/752 ...

**Pull request merged**
