### PR TITLE
Secure headers fixes

### PR DESCRIPTION
**Pull request by ajgon**

### CODE REVIEW

**Comment by jondeandres** [comment]
Thank you very much for this @ajgon. I'll need to try it but it looks fine.

Do you know this will work fine for SecureHeaders 2.x? https://github.com/twitter/secureheaders/blob/2.x/README.md

Thanks

**Comment by ajgon** [comment]
@jondeandres It should since the original checks for middleware are still there as well.

**Comment by spdawson** [comment]
Any progress on this?

**Comment by jondeandres** [comment]
hey @spdawson, sorry for the delay. I'll need to test it and I'll merge. We hope to do it during this week.

Thanks.

**Comment by jondeandres** [comment]
@ajgon I've opened a PR, https://github.com/rollbar/rollbar-gem/pull/478, with your commits and few more.

I think we need to maintain the loading order we had. We want always to add the middleware inside a `execute do ` block since we are sure on that moment that `Rollbar.configure` was called and  we have the correct configuration values.

Also I fixed some tests issues with old rubies. I'll merge my PR so this PR will be closed automatically by Github

**Comment by jondeandres** [comment]
@ajgon any opinion for my last comment?

Thanks!

**Comment by ajgon** [comment]
@jondeandres Hey, I tried your PR with SecureHeaders 3 and JS enabled, but I can't see rollbar.js added to the body. Have you tried it with SH3+Rails app?

I can set up a simple Rails App repository for you, with SH3 and Rollbar configured, to show you the issue.

**Comment by jondeandres** [comment]
@ajgon I have a rails project with secure headers 3 and the middleware is being added correctly.

Can you show us your Rollbar configuration?

if you push an example repository reproducing the problem it'd be awesome, yes.

Thanks!

**Comment by ajgon** [comment]
Here is the config:

```ruby
# frozen_string_literal: true
def rollbar_code_version
  ref = if File.exist?(Rails.root.join('.git/HEAD'))
          File.read(Rails.root.join('.git/HEAD')).strip
        else
          SecureRandom.hex(20)
        end
  ref = (ref.start_with?('ref:') ? File.read(Rails.root.join(".git/#{ref[5..-1]}")) : ref).strip
  ref =~ /^[0-9a-f]+$/ ? ref : SecureRandom.hex(20)
end

Rollbar.configure do |config|
  secret_file = ENV['ROLLBAR_ENV'].present? ? "secrets/#{ENV['ROLLBAR_ENV']}.yml" : 'secrets.yml'
  secrets = YAML.load(ERB.new(File.read(Rails.root.join('config', secret_file))).result)[Rails.env]

  config.access_token = secrets['rollbar']['post_server_item']

  config.person_method = 'current_user'
  config.person_id_method = 'id'
  config.person_username_method = 'name'
  config.person_email_method = 'email'

  config.exception_level_filters['ActionController::InvalidAuthenticityToken'] = 'ignore'

  config.use_sidekiq
  config.environment = ENV['ROLLBAR_ENV'] || Rails.env

  # rollbar.js
  source_map_payload = if ENV['ENABLE_SOURCE_MAPS']
                         {
                           client: {
                             javascript: {
                               source_map_enabled: true,
                               code_version: rollbar_code_version,
                               guess_uncaught_frames: true
                             }
                           }
                         }
                       else
                         {}
                       end
  config.js_enabled = true
  config.js_options = {
    accessToken: secrets['rollbar']['post_client_item'],
    rollbarJsUrl: 'https://cdn.rollbar.com/js/v1.9/rollbar.min.js',
    captureUncaught: true,
    payload: {
      environment: Rails.env
    }.merge(source_map_payload)
  }
end if Rails.env.production?
```

I'll set up and example app later this day.
Maybe it is caused by the fact, that I'm invoking this from `config/rollbar.rb` [as described here](https://github.com/rollbar/rollbar-gem#rails-booting-process) instead of `config/initializers/rollbar.rb` ?

**Comment by jondeandres** [comment]
@ajgon oh...I think that can have sense...since with `config/rollbar.rb` we are changing the rails bootup process. if you can move to `config/initializer/rollbar.rb` just to check it works as you expect, that'd be nice. we would need to figure out how to support both scenarios.

**Comment by ajgon** [comment]
Hey I believe I nailed the problem in my app. It is casued by the `react-rails` gem - I'll investigate it further later on. I tested it with dummy Rails app and it worked as expected 👍

**Comment by jondeandres** [comment]
@ajgon awesome, I guess you tried the branch for the PR I opened? #478 

If you arrive to any conclusion please share with us :smile:

**Comment by ajgon** [comment]
Yes, I used `jon/secure-headers-fixes` for testing :)

**Pull request merged**
